stages:
  data_ingestion:
    cmd: python ./src/data/data_ingestion.py
    deps:
      - ./src/data/data_ingestion.py
      - ./data/raw/zipped/data.zip
    outs:
      - ./data/raw/extracted
      - ./data/interim/
  
  data_transformation:
    cmd : python ./src/data/data_transformation.py
    deps:
      - ./src/data/data_transformation.py
      - ./data/interim/
    outs:
      - ./data/processed/
  
  model_trainer:
    cmd: python ./src/models/model_trainer.py
    deps:
      - ./data/processed/
    outs:
      - ./models/trained_models